# from app import db, app, Book, User, RegisterForm
from library import *
from library.models import *

with app.app_context():
    db.create_all()
    # book1 = Book(name="Dragon Ball Z", author='Unknown', price=10)
    # book2 = Book(name="Goku - A Super Sayian", price=40)
    # book3 = Book(name="Vegeta - The Pride", price=30)
    book4 = Book(name="1984", author='George Orwell', price=30)
    book5 = Book(name="The Lord of the Rings", author='J.R.R. Tolkien', price=30)
    book6 = Book(name="The Kite Runner", author='Khaled Hosseini', price=30)
    book7 = Book(name="Harry Potter and the Philosopher’s Stone", author='J.K. Rowling', price=30)
    book8 = Book(name="Slaughterhouse-Five", author='Kurt Vonnegut', price=30)
    book9 = Book(name="The Lion, the Witch, and the Wardrobe", author='C.S. Lewis', price=30)
    book10 = Book(name="To Kill a Mockingbird ", author='Harper Lee', price=30)
    book11 = Book(name="The Book Thief", author='Markus Zusak', price=30)
    book12 = Book(name="Wuthering Heights", author=' Emily Bronte', price=30)
    book13 = Book(name="The Catcher in the Rye", author='J.D. Salinger', price=30)
    book14 = Book(name="Jane Eyre", author='Charlotte Bronte', price=30)
    book15 = Book(name="Animal Farm", author='George Orwell', price=30)
    book16 = Book(name="Fahrenheit 451", author='Ray Bradbury', price=30)
    book17 = Book(name="Little Women", author='Louisa May Alcott', price=30)
    book18 = Book(name="Charlotte’s Web", author='E.B. White', price=30)
    book19 = Book(name=" Frankenstein", author='Mary Shelley', price=30)
    book20 = Book(name="Of Mice and Men", author='John Steinbeck', price=30)
    book21 = Book(name="The Hitchhiker’s Guide to the Galaxy", author='Douglas Adams', price=30)
    book22 = Book(name="The Great Gatsby", author='F. Scott Fitzgerald', price=30)
    book23 = Book(name="Think and Grow Rich", author='Napoleon Hill', price=30)
    book24 = Book(name="Rich Dad Poor Dad", author='Robert T. Kiyosaki', price=30)
    book25 = Book(name="The Intelligent Investor", author='Benjamin Graham', price=30)
    book26 = Book(name="Principles: Life and Work", author='Ray Dalio', price=30)
    book27 = Book(name="Influence: The Psychology of Persuasion", author='Robert B. Cialdini', price=30)
    book28 = Book(name="How to Win Friends and Influence People", author='Dale Carnegie', price=30)
    book29 = Book(name="The Power of Habit", author='Charles Duhigg', price=30)
    book30 = Book(name="The Power of Now", author='Eckhart Tolle', price=30)
    book31 = Book(name="The Body Keeps the Score", author='Bessel van der Kolk M.D', price=30)
    book32 = Book(name="A Brief History of Time", author='Stephen Hawking', price=30)
    book33 = Book(name="Freakonomics", author='Steven D. Levitt', price=30)
    book34 = Book(name="The Age of Surveillance Capitalism", author='Shoshana Zuboff', price=30)
    book35 = Book(name="Uncanny Valley", author='Anna Wiener', price=30)
    book36 = Book(name="On the Road", author='Jack Kerouac', price=30)
    book37 = Book(name="Notes from a Small Island", author='Bill Bryson', price=30)
    book38 = Book(name="Sapiens", author='Yuval Noah Harari', price=30)
    book39 = Book(name="Wild", author='Cheryl Strayed', price=30)
    book40 = Book(name=" Long Walk to Freedom", author='Nelson Mandela', price=30)
    book41 = Book(name="The Rise and Fall of the Dinosaurs", author='Steve Brusatte', price=30)
    book42 = Book(name="A Short History of Nearly Everything", author='Bill Bryson', price=30)

    # db.session.add(book1)
    # db.session.add(book2)
    # db.session.add(book3)
    db.session.add(book4)
    db.session.add(book5)
    db.session.add(book6)
    db.session.add(book7)
    db.session.add(book8)
    db.session.add(book9)
    db.session.add(book10)
    db.session.add(book11)
    db.session.add(book12)
    db.session.add(book13)
    db.session.add(book14)
    db.session.add(book15)
    db.session.add(book16)
    db.session.add(book17)
    db.session.add(book18)
    db.session.add(book19)
    db.session.add(book20)
    db.session.add(book21)
    db.session.add(book22)
    db.session.add(book23)
    db.session.add(book24)
    db.session.add(book25)
    db.session.add(book26)
    db.session.add(book27)
    db.session.add(book28)
    db.session.add(book29)
    db.session.add(book30)
    db.session.add(book31)
    db.session.add(book32)
    db.session.add(book33)
    db.session.add(book34)
    db.session.add(book35)
    db.session.add(book36)
    db.session.add(book37)
    db.session.add(book38)
    db.session.add(book39)
    db.session.add(book40)
    db.session.add(book41)
    db.session.add(book42)

    db.session.commit()
    Book.query.all()
    admin = User(username="Nalin", email_address="nalin.mail.smtp@gmail.com", password="Nalin@1234", is_admin=True)
    user1 = User(username="Nalin1", email_address="nalingupta71@gmail.com", password="Nalin123")
    db.session.add(admin)
    db.session.add(user1)
    db.session.commit()
    User.query.all()

    # book1.owners.append(admin)
    book4.owners.append(user1)
    db.session.commit()

    i = Book.query.filter_by(name='Dragon Ball Z').first()
    # print(i.owners)



